### ISSUE TITLE
Multiboxing in BG

### ISSUE THREAD

**Issue by tangvis** [KocsiLevente/multibox#1]
Hey dude, do you have some suggestions for multi-boxing in battleground while the /follow is disbled?
I wrote my own keyclone program for multiboxing, but when i entered the warsong bg, i sadly found that the /follow is forbidden.

**Comment by KocsiLevente** [comment]
> Hey dude, do you have some suggestions for multi-boxing in battleground while the /follow is disbled?
> I wrote my own keyclone program for multiboxing, but when i entered the warsong bg, i sadly found that the /follow is forbidden.

Hey :) I haven't used my multibox characters on BGs yet because I'm focused on PvE but I would try the Follow() command within the lua code instead of using /follow. If it isn't working then I would share all of the mowement keys (WASD) and try to move the characters together. I think you use HotKeyNet too, don't you?

**Comment by palfibeni** [comment]
only the /follow macro is forbidden, right click on target and following is still useable?

**Comment by tangvis** [comment]
close
